[pytest]
minversion = 7.0
DJANGO_SETTINGS_MODULE = yanews.settings
testpaths =
    pytest_trial
    news/tests
addopts = -v --strict-markers
markers =
    slow: Very slow tests
    web: Tests with external API
python_files = test_*.py check_*.py
python_classes = Test* Check*
python_functions = test_* *_check
